### ISSUE TITLE
Using SDL.Cairo.Canvas without SDL

### ISSUE THREAD

**Issue by noinia** [apirogov/sdl2-cairo#1]
The Canvas processing style API is wonderful for creating drawings, and it seems to be exactly what I need. However, after some deliberation I've decided to use gi-gtk in my application rather than SDL, but I would like to keep using your Canvas style API for drawing. If the SDL.Cairo.Canvas module would export a function that maps a 'Canvas a' into a 'Render a' this would be possible. Would you be open for such a change? 

I implemented those changes in my local fork (https://github.com/noinia/sdl2-cairo). In particular, I

1) added and exported the functions withCairoSurface, withRenderer that did most of the work that was previously in 'withCanvas' 
2) removed the 'csSurface' field in CanvasState, and used 'Graphics.Rendering.Cairo.withTargetSurface' to implement 'blend' and 'grab' instead (gi-gtk doesn't know about cairo Surfaces, and hence I needed everything to be in the Render monad itself (see [here](https://github.com/noinia/hgeometry/blob/master/interactive/CairoSimple.hs#L33) for an example of how this is used)

I can send a pull request if you want. I guess ideally there would also be a flag to disable the dependency on SDL all together (/have the Canvas stuff in its own package or so). But for now I would already be happy to be able to use the Canvas stuff in gi-gtk :).

**Comment by apirogov** [comment]
Great idea! I'm totally for generalizing it.

I split the package into sdl2-cairo (this repo) with the glue code and [cairo-canvas](http://github.com/apirogov/cairo-canvas) with the rest and included your changes in the latter. If you have any issues or improvements, open an issue there!
